env:
  browser: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  ActionCable: true
  module: true
  process: true

  # spec/javascript/setup.js
  global: true
  mount: true
  React: true
  shallow: true
  sinon: true
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  arrow-body-style:
    - error
    - as-needed
  no-duplicate-imports:
    - error
  object-shorthand:
    - warn
  quotes:
    - error
    - single
  react/prop-types:
    - error
    - skipUndeclared: true
  semi:
    - warn
    - never
  sort-imports:
    - warn
  sort-vars:
    - warn
