env:
  browser: true
  es6: true
  jest: true
extends: 'eslint:recommended'
globals:
  ActionCable: true
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  arrow-body-style:
    - error
    - as-needed
  no-duplicate-imports:
    - error
  object-shorthand:
    - warn
  quotes:
    - error
    - single
  semi:
    - warn
    - never
  sort-imports:
    - warn
  sort-vars:
    - warn
