AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true  

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
