AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*

Layout/IndentArray:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - lib/tasks/build.rake
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
