version: "3"
services:
  rails:
    build: .
    ports:
     - 3000:3000
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - node_modules:/app/node_modules
      - public:/app/public
      - tmp:/app/tmp
      - .:/app
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEBPACKER_DEV_SERVER_PUBLIC=webpacker:3035
  webpacker:
    build: .
    ports:
     - 3035:3035
    command: bundle exec webpack-dev-server
    volumes:
      - node_modules:/app/node_modules
      - public:/app/public
      - tmp:/app/tmp
      - .:/app
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - WEBPACKER_DEV_SERVER_PUBLIC=0.0.0.0:3035
volumes:
  node_modules:
  public:
  tmp:
